version: '3'

services:

  parsingjob:
    image: parsingjob
    hostname: parsingjob
    container_name: parsingjob
    restart: always
    expose:
      - 20081
    build:
      context: .
      dockerfile: Vinyl.ParsingJob/Dockerfile
    environment:
      DB_CONNECTION_STRING: "host=postgresdb;port=5432;database=vinylshop;username=dbuser;password=dbpwd"   
      PROXY_PREFIX: "parsing"
      CLEAR_DB: "0"
      KAFKA_DIRTY_RECORDS_TOPIC: "dirty_records"
      KAFKA_CONNECT: "kafka:9092"
    networks:
      - vinylnetwork

networks:
  vinylnetwork:
     driver: bridge
     
