version: '3'

services:

  postgresserver:
    image: postgres
    hostname: postgresdb
    container_name: postgresdb
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpwd"
      POSTGRES_DB: "vinylshop"
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - vinylnetwork

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181
    networks:
      - vinylnetwork

  kafka:
    image: wurstmeister/kafka:1.0.0
    hostname: kafka
    container_name: kafka
    restart: always
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      KAFKA_JMX_OPTS: -Xms256m -Xmx256m
      KAFKA_HEAP_OPTS: -Xmx256M -Xms256M
      KAFKA_CREATE_TOPICS: "dirty_records:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181    
      KAFKA_BROKER_ID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vinylnetwork

  parsingjob:
    image: martinistation/parsingjob
    hostname: parsingjob
    container_name: parsingjob
    restart: always
    links:
      - kafka
      - postgresserver
    expose:
      - 20081
    build:
      context: .
      dockerfile: Vinyl.ParsingJob/Dockerfile
    environment:
      DB_CONNECTION_STRING: "host=postgresdb;port=5432;database=vinylshop;username=dbuser;password=dbpwd"   
      PROXY_PREFIX: "parsing"
    networks:
      - vinylnetwork

  recordprocessingjob:
    image: martinistation/recordprocessingjob
    hostname: recordprocessingjob
    container_name: recordprocessingjob      
    restart: always
    links:
      - kafka
      - postgresserver
    expose:
      - 20082
    build:
      context: .
      dockerfile: Vinyl.RecordProcessingJob/Dockerfile
    environment:
      DB_CONNECTION_STRING: "host=postgresdb;port=5432;database=vinylshop;username=dbuser;password=dbpwd"
      PROXY_PREFIX: "processing"
    networks:
      - vinylnetwork

  site:
    image: martinistation/site
    hostname: site
    container_name: site
    restart: always
    links:
      - kafka
      - postgresserver
    expose:
      - 20080
    build:
      context: .
      dockerfile: Vinyl.Site/Dockerfile
    networks:
      - vinylnetwork

  nginxproxy:
    image: martinistation/nginxproxy
    hostname: nginxproxy
    container_name: nginxproxy
    restart: always
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - recordprocessingjob
      - parsingjob
      - site
      - kafka
      - postgresserver
    networks:
      - vinylnetwork

networks:
  vinylnetwork:
     driver: bridge

volumes:
  pgdata:
