version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "dirty_records:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  vinyl.parsingjob:
    image: vinyl.parsingjob
    ports:
      - "20081:20081"
    build:
      context: ./Vinyl.ParsingJob
      dockerfile: Dockerfile

  vinyl.recordprocessingjob:
    image: vinyl.recordprocessingjob
    ports:
      - "20082:20082"
    build:
      context: ./Vinyl.RecordProcessingJob
      dockerfile: Dockerfile
