version: '3'

services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:1.0.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.225.164
      KAFKA_CREATE_TOPICS: "dirty_records:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181    
      KAFKA_BROKER_ID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  vinyl.parsingjob:
    image: vinyl.parsingjob
    hostname: parsingjob
    container_name: parsingjob
    depends_on:
      - kafka
    ports:
      - "20081:20081"
    build:
      context: ./Vinyl.ParsingJob
      dockerfile: Dockerfile

  vinyl.recordprocessingjob:
    image: vinyl.recordprocessingjob
    hostname: recordprocessingjob
    container_name: recordprocessingjob
    depends_on:
      - kafka
    ports:
      - "20082:20082"
    build:
      context: ./Vinyl.RecordProcessingJob
      dockerfile: Dockerfile
